services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "5001:5001"   # HTTP
      - "5052:5052"   # gRPC
    environment:
      - MONGO_URI=mongodb://mongodb:27017/user-service
      - PORT=5001
      - GRPC_PORT=0.0.0.0:5052
      - JWT_SECRET=JESUSILOVEYOU
      - JWT_EXPIRY=1d
    depends_on:
      - mongodb
    networks:
      - app-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "3001:3001"   # HTTP
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/order_db?schema=public
      - USER_SERVICE_URL=user-service:5052
      - JWT_SECRET=JESUSILOVEYOU
      - PORT=3001
    depends_on:
      - postgres
      - user-service
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - AUTH_JWT_SECRET=JESUSILOVEYOU
      - USER_SERVICE_URL=http://user-service:5001
      - ORDER_SERVICE_URL=http://order-service:3001
      - RATE_LIMIT_WINDOW=15
      - RATE_LIMIT_MAX_REQUESTS=100
    depends_on:
      - user-service
      - order-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  postgres_data:
