apiVersion: v1
kind: Secret
metadata:
  name: grpc-project-secrets
type: Opaque
data:
  # Values must be base64 encoded
  # Tip: echo -n "your-value" | base64
  
  # Placeholder for JWT_SECRET
  JWT_SECRET: "<base64-encoded-jwt-secret>"
  
  # Placeholder for MONGODB_URI
  MONGODB_URI: "<base64-encoded-mongodb-uri>"
  
  # Placeholder for DATABASE_URL (PotgreSQL)
  DATABASE_URL: "<base64-encoded-database-url>"
